# Generated by Django 2.2.4 on 2020-09-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
